/**
 * export-bootstrap.ts
 *
 * Queries the live Neo4j database and exports all data as an idempotent .cypher file
 * suitable for bootstrapping a fresh Neo4j instance.
 *
 * Usage: npx tsx src/scripts/export-bootstrap.ts
 * Output: packages/server/db/bootstrap.cypher
 */

import { createDriver, closeDriver } from "../services/graph/neo4j.js";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, "../../db/bootstrap.cypher");

const NEO4J_URI = process.env.NEO4J_URI ?? "bolt://localhost:7687";
const NEO4J_USER = process.env.NEO4J_USER ?? "neo4j";
const NEO4J_PASSWORD = process.env.NEO4J_PASSWORD ?? "password";

interface CypherStatement {
  text: string;
  params: Record<string, unknown>;
}

async function main() {
  console.log(`Connecting to ${NEO4J_URI}...`);
  createDriver({ uri: NEO4J_URI, user: NEO4J_USER, password: NEO4J_PASSWORD });

  const { runQuery } = await import("../services/graph/neo4j.js");

  const lines: string[] = [];
  lines.push("// ============================================================");
  lines.push("// LeadGraph Bootstrap Cypher");
  lines.push("// Generated by export-bootstrap.ts — all statements are idempotent");
  lines.push("// ============================================================\n");

  // ── 1. Constraints (idempotent) ──
  lines.push("// ── Constraints ──");
  lines.push("CREATE CONSTRAINT IF NOT EXISTS FOR (c:Company) REQUIRE c.normalizedName IS UNIQUE;");
  lines.push("CREATE CONSTRAINT IF NOT EXISTS FOR (a:Application) REQUIRE a.name IS UNIQUE;");
  lines.push("CREATE CONSTRAINT IF NOT EXISTS FOR (p:Product) REQUIRE p.catalogId IS UNIQUE;");
  lines.push("CREATE INDEX IF NOT EXISTS FOR (s:Signal) ON (s.type);");
  lines.push("");

  // ── 2. Applications ──
  console.log("Exporting Applications...");
  const apps = await runQuery(
    "MATCH (a:Application) RETURN a.name AS name, a.category AS category ORDER BY a.name"
  );
  if (apps.records?.length) {
    lines.push("// ── Applications ──");
    for (const app of apps.records as Array<{ name: string; category: string }>) {
      const name = esc(app.name);
      const cat = esc(app.category ?? "");
      lines.push(
        `MERGE (a:Application {name: ${name}}) SET a.category = ${cat};`
      );
    }
    lines.push("");
  }

  // ── 3. Products ──
  console.log("Exporting Products...");
  const products = await runQuery(
    "MATCH (p:Product) RETURN p.catalogId AS catalogId, p.name AS name, p.category AS category ORDER BY p.catalogId"
  );
  if (products.records?.length) {
    lines.push("// ── Products ──");
    for (const p of products.records as Array<{ catalogId: string; name: string; category: string }>) {
      const cid = esc(p.catalogId);
      const name = esc(p.name ?? "");
      const cat = esc(p.category ?? "");
      lines.push(`MERGE (p:Product {catalogId: ${cid}}) SET p.name = ${name}, p.category = ${cat};`);
    }
    lines.push("");
  }

  // ── 4. Companies ──
  console.log("Exporting Companies...");
  const companies = await runQuery(
    `MATCH (c:Company)
     RETURN c.normalizedName AS normName, c.name AS name, c.domain AS domain,
            c.description AS description, c.segment AS segment, c.region AS region
     ORDER BY c.normalizedName`
  );
  if (companies.records?.length) {
    lines.push("// ── Companies ──");
    for (const c of companies.records as Array<{
      normName: string; name: string; domain: string | null;
      description: string | null; segment: string | null; region: string | null;
    }>) {
      const nn = esc(c.normName);
      const name = esc(c.name);
      const domain = esc(c.domain ?? "");
      const desc = esc(c.description ?? "");
      const seg = esc(c.segment ?? "");
      const reg = esc(c.region ?? "");
      lines.push(
        `MERGE (c:Company {normalizedName: ${nn}}) ` +
        `SET c.name = ${name}, c.domain = ${domain}, c.description = ${desc}, ` +
        `c.segment = ${seg}, c.region = ${reg};`
      );
    }
    lines.push("");
  }

  // ── 5. Product→Application relationships ──
  console.log("Exporting Product→Application relationships...");
  const prodApps = await runQuery(
    `MATCH (p:Product)-[r:USED_IN]->(a:Application)
     RETURN p.catalogId AS catalogId, a.name AS appName`
  );
  if (prodApps.records?.length) {
    lines.push("// ── Product → Application ──");
    for (const rel of prodApps.records as Array<{ catalogId: string; appName: string }>) {
      const cid = esc(rel.catalogId);
      const app = esc(rel.appName);
      lines.push(
        `MATCH (p:Product {catalogId: ${cid}}), (a:Application {name: ${app}}) ` +
        `MERGE (p)-[:USED_IN]->(a);`
      );
    }
    lines.push("");
  }

  // ── 6. Company→Application relationships ──
  console.log("Exporting Company→Application relationships...");
  const compApps = await runQuery(
    `MATCH (c:Company)-[r:DEVELOPS]->(a:Application)
     RETURN c.normalizedName AS normName, a.name AS appName`
  );
  if (compApps.records?.length) {
    lines.push("// ── Company → Application ──");
    for (const rel of compApps.records as Array<{ normName: string; appName: string }>) {
      const nn = esc(rel.normName);
      const app = esc(rel.appName);
      lines.push(
        `MATCH (c:Company {normalizedName: ${nn}}), (a:Application {name: ${app}}) ` +
        `MERGE (c)-[:DEVELOPS]->(a);`
      );
    }
    lines.push("");
  }

  // ── 7. Company→Product relationships ──
  console.log("Exporting Company→Product relationships...");
  const compProds = await runQuery(
    `MATCH (c:Company)-[r:SUPPLIES]->(p:Product)
     RETURN c.normalizedName AS normName, p.catalogId AS catalogId`
  );
  if (compProds.records?.length) {
    lines.push("// ── Company → Product ──");
    for (const rel of compProds.records as Array<{ normName: string; catalogId: string }>) {
      const nn = esc(rel.normName);
      const cid = esc(rel.catalogId);
      lines.push(
        `MATCH (c:Company {normalizedName: ${nn}}), (p:Product {catalogId: ${cid}}) ` +
        `MERGE (c)-[:SUPPLIES]->(p);`
      );
    }
    lines.push("");
  }

  // ── 8. Signals + HAS_SIGNAL (dedup by type+date+description) ──
  console.log("Exporting Signals...");
  const signals = await runQuery(
    `MATCH (c:Company)-[r:HAS_SIGNAL]->(s:Signal)
     RETURN c.normalizedName AS normName, s.type AS type, s.date AS date,
            s.description AS description, s.confidence AS confidence, s.url AS url
     ORDER BY c.normalizedName, s.type, s.date`
  );
  if (signals.records?.length) {
    lines.push("// ── Signals ──");
    // Use MERGE on the dedup key (type+date+description) so it's idempotent
    for (const sig of signals.records as Array<{
      normName: string; type: string; date: string;
      description: string; confidence: number; url: string | null;
    }>) {
      const nn = esc(sig.normName);
      const type = esc(sig.type);
      const date = esc(sig.date);
      const desc = esc(sig.description);
      const conf = sig.confidence ?? 0.5;
      const url = esc(sig.url ?? "");
      lines.push(
        `MATCH (c:Company {normalizedName: ${nn}}) ` +
        `MERGE (s:Signal {type: ${type}, date: ${date}, description: ${desc}}) ` +
        `ON CREATE SET s.confidence = ${conf}, s.url = ${url} ` +
        `MERGE (c)-[:HAS_SIGNAL]->(s);`
      );
    }
    lines.push("");
  }

  // ── 9. Pipeline Stages ──
  console.log("Exporting Pipeline Stages...");
  const stages = await runQuery(
    "MATCH (ps:PipelineStage) RETURN ps.stage AS stage, ps.enteredAt AS enteredAt ORDER BY ps.stage"
  );
  if (stages.records?.length) {
    lines.push("// ── Pipeline Stages ──");
    for (const ps of stages.records as Array<{ stage: string; enteredAt: string | null }>) {
      const stage = esc(ps.stage);
      const entered = esc(ps.enteredAt ?? "");
      lines.push(`MERGE (ps:PipelineStage {stage: ${stage}}) SET ps.enteredAt = ${entered};`);
    }
    lines.push("");
  }

  // ── 10. Contacts + relationships ──
  console.log("Exporting Contacts...");
  const contacts = await runQuery(
    `MATCH (ct:Contact)
     OPTIONAL MATCH (ct)-[:CONTACT_AT]->(comp:Company)
     RETURN ct.name AS name, ct.email AS email, ct.role AS role,
            comp.normalizedName AS companyNormName`
  );
  if (contacts.records?.length) {
    lines.push("// ── Contacts ──");
    for (const ct of contacts.records as Array<{
      name: string; email: string | null; role: string | null; companyNormName: string | null;
    }>) {
      const name = esc(ct.name);
      const email = esc(ct.email ?? "");
      const role = esc(ct.role ?? "");
      // Create contact with a deterministic UUID based on name
      const contactId = `contact-${ct.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}`;
      lines.push(
        `MERGE (ct:Contact {name: ${name}}) ` +
        `ON CREATE SET ct.email = ${email}, ct.role = ${role} ` +
        `ON MATCH SET ct.email = ${email}, ct.role = ${role};`
      );
      if (ct.companyNormName) {
        const nn = esc(ct.companyNormName);
        lines.push(
          `MATCH (ct:Contact {name: ${name}}), (comp:Company {normalizedName: ${nn}}) ` +
          `MERGE (ct)-[:CONTACT_AT]->(comp);`
        );
      }
    }
    lines.push("");
  }

  // ── 11. Activities + HAS_ACTIVITY ──
  console.log("Exporting Activities...");
  const activities = await runQuery(
    `MATCH (ct:Contact)-[r:HAS_ACTIVITY]->(act:Activity)
     RETURN ct.name AS contactName, act.type AS type, act.note AS note,
            act.date AS date
     ORDER BY act.date`
  );
  if (activities.records?.length) {
    lines.push("// ── Activities ──");
    for (const a of activities.records as Array<{
      contactName: string; type: string; note: string | null; date: string;
    }>) {
      const cn = esc(a.contactName);
      const type = esc(a.type);
      const note = esc(a.note ?? "");
      const date = esc(a.date);
      lines.push(
        `MATCH (ct:Contact {name: ${cn}}) ` +
        `CREATE (act:Activity {type: ${type}, note: ${note}, date: ${date}}) ` +
        `MERGE (ct)-[:HAS_ACTIVITY]->(act);`
      );
    }
    lines.push("");
  }

  // ── 12. Contact→IN_STAGE→PipelineStage ──
  console.log("Exporting Contact→Stage relationships...");
  const contactStages = await runQuery(
    `MATCH (ct:Contact)-[r:IN_STAGE]->(ps:PipelineStage)
     RETURN ct.name AS contactName, ps.stage AS stage`
  );
  if (contactStages.records?.length) {
    lines.push("// ── Contact → Pipeline Stage ──");
    for (const cs of contactStages.records as Array<{ contactName: string; stage: string }>) {
      const cn = esc(cs.contactName);
      const stage = esc(cs.stage);
      lines.push(
        `MATCH (ct:Contact {name: ${cn}}), (ps:PipelineStage {stage: ${stage}}) ` +
        `MERGE (ct)-[:IN_STAGE]->(ps);`
      );
    }
    lines.push("");
  }

  // Write output
  const output = lines.join("\n");
  mkdirSync(dirname(OUTPUT), { recursive: true });
  writeFileSync(OUTPUT, output, "utf-8");
  console.log(`\n✅ Bootstrap Cypher written to ${OUTPUT}`);
  console.log(`   ${lines.length} lines, ~${(Buffer.byteLength(output) / 1024).toFixed(1)} KB`);

  await closeDriver();
}

function esc(s: string): string {
  // Neo4j Cypher string escaping: double inner quotes
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

main().catch((err) => {
  console.error("Export failed:", err);
  process.exit(1);
});
