/**
 * run-bootstrap.ts
 *
 * Reads the bootstrap Cypher file generated by export-bootstrap.ts
 * and executes it against a running Neo4j instance.
 *
 * Used by:
 *   - docker-compose bootstrap service (auto-run on fresh install)
 *   - npm run db:bootstrap (manual local use)
 *
 * Usage: npx tsx src/scripts/run-bootstrap.ts
 */

import { createDriver, closeDriver } from "../services/graph/neo4j.js";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BOOTSTRAP_FILE = resolve(__dirname, "../../db/bootstrap.cypher");

const NEO4J_URI = process.env.NEO4J_URI ?? "bolt://localhost:7687";
const NEO4J_USER = process.env.NEO4J_USER ?? "neo4j";
const NEO4J_PASSWORD = process.env.NEO4J_PASSWORD ?? "password";

async function main() {
  console.log(`Connecting to ${NEO4J_URI}...`);
  createDriver({ uri: NEO4J_URI, user: NEO4J_USER, password: NEO4J_PASSWORD });
  const { runQuery } = await import("../services/graph/neo4j.js");

  // Verify connection
  const { verifyConnection } = await import("../services/graph/neo4j.js");
  if (!(await verifyConnection())) {
    throw new Error("Cannot connect to Neo4j — is it running?");
  }
  console.log("Connected.\n");

  const cypher = readFileSync(BOOTSTRAP_FILE, "utf-8");
  const statements = cypher
    .split(";")
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && !s.startsWith("//") && s !== "\n");

  console.log(`Loaded ${statements.length} statements from bootstrap.cypher\n`);

  // Execute in batches of 50 for progress tracking + memory safety
  const BATCH_SIZE = 50;
  let total = 0;
  let errors = 0;

  for (let i = 0; i < statements.length; i += BATCH_SIZE) {
    const batch = statements.slice(i, i + BATCH_SIZE);
    const batchNum = Math.floor(i / BATCH_SIZE) + 1;
    const totalBatches = Math.ceil(statements.length / BATCH_SIZE);

    for (const stmt of batch) {
      try {
        await runQuery(stmt + ";");
        total++;
      } catch (err) {
        errors++;
        const msg = err instanceof Error ? err.message : String(err);
        // Log first few chars of the statement for debugging
        const snippet = stmt.slice(0, 80).replace(/\n/g, " ");
        console.error(`  ✗ Error [${snippet}...]: ${msg}`);
      }
    }

    const pct = ((batchNum / totalBatches) * 100).toFixed(1);
    console.log(`  Batch ${batchNum}/${totalBatches} (${pct}%) — ${total} ok, ${errors} errors`);
  }

  console.log(`\n✅ Bootstrap complete: ${total} statements executed, ${errors} errors`);
  await closeDriver();
}

main().catch((err) => {
  console.error("Bootstrap failed:", err);
  process.exit(1);
});
